version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/app.dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/novocaine-dev
    depends_on:
      - database
    container_name: novocaine-dev-web
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'

  database:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: novocaine-dev
    container_name: novocaine-dev-db
    ports:
      - 33066:3306
    volumes:
      - novocaine-dev-data:/var/lib/mysql 

  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - 5003:80
    environment:
      - 'PMA_HOST=database'
      - 'PMA_PORT=3306'
    container_name: novocaine-dev-pma


# persisted storage
volumes:
  novocaine-dev-data: